### ISSUE TITLE
state is undefined in exported selector function 

### ISSUE THREAD

**Issue by AnnaLinnIsabelle** [ngrx/example-app#167]
I am following the structure in the example app trying to retrieve a slice of state in a container component. My child reducer consists of the following code:

```
import * as employeeActions from '../actions/employee.actions';

export interface State {
  authenticated: boolean;
  loading: boolean;
  authorized: boolean;
  error?: string;
  employee?: object;
};

export const initialState: State = {
  authenticated: false,
  loading: false,
  authorized: false
};

export function employeeReducer(state = initialState, action: employeeActions.Actions): State {
  console.log('Action came in! ' + action.type);
  switch (action.type) {
    case employeeActions.AUTHENTICATE_EMPLOYEE: {
      return Object.assign({}, state, {loading:true});
    }
    case employeeActions.AUTHENTICATE_SUCCESS: {
      return Object.assign({}, state, {loading: false, authenticated: true, employee: action.payload});
    }
    case employeeActions.AUTHENTICATE_FAILURE: {
      console.log(action.payload);
      return Object.assign({},state,{loading: false, error: action.payload});
    }
    default:{
      return state;
    }
  }
}

export const getAuthenticated = (state: State) => state.authenticated;
export const getLoading = (state: State) => state.loading;
export const getAuthorized = (state: State) => state.authorized;
export const getEmployee = (state: State) => state.employee;

```

at `"export const  getEmployee = (state: State) => state.employee"` i recieve this error:

```
 "ERROR TypeError: Cannot read property 'employee' of undefined
    at getEmployee "
```

I have a metareducer using the childreducers selector function like so:
```
"export const getEmployeeInfo = createSelector(getEmployeeState, fromEmployeeReducers.getEmployee);"
```

The metareducers selector function is called from the container component like so:
```
  constructor( private store: Store<fromRoot.State>,
    ) {
    this.employee$ = store.select(fromRoot.getEmployeeInfo);
  }
```

What is causing this error?

**Comment by krjordan** [comment]
I've run into this issue when using data from an API call. If the call hasn't returned any data yet, you will have an undefined object. If this is the case, adding a conditional to make sure there is an object should fix it. Something like: 

`export const getEmployee = (state: State) => state.employee ? state.employee : null;`

**Comment by piq9117** [comment]
you can also set it in the `initialState`
```
export const initialState: State = {
  authenticated: false,
  loading: false,
  authorized: false,
  employee: {}
};
```

**Comment by AnnaLinnIsabelle** [comment]
No, that doesn't seem to solve it. As far as I understand, it is the **state** in this call,

"export const getEmployee = (state: State) => state.employee"

not the employee that is undefined.

**Comment by roopkt** [comment]
Can you show where is your combined reducers?  It should match with the
individual state name.

const reducers = {
employee : fromemployee.reducer,
// make sure the key is employee same as // app state key name.
....
}

If your reducers key name does not match with app state key names it will
come as undefined.

const appState= {
 employee: fromemployee.state
 // make sure key name is employee
...
 }

Hope this helps!



On Jul 12, 2017 2:18 AM, "AnnaLinnIsabelle" <notifications@github.com>
wrote:

No, that doesn't seem to solve it. As far as I understand, it is the *state*
in this call,

"export const getEmployee = (state: State) => state.employee"

not the employee that is undefined.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ngrx/example-app/issues/167#issuecomment-314665575>,
or mute
the thread

**Comment by roopkt** [comment]
Can you show where is your combined reducers?  It should match with the
individual state name.

``` 
const reducers = {
    employee : fromEmployee.reducer,   
    // make sure the key is employee same as app state key name.
     ....
}
 ```

If your reducers key name does not match with app state key names it will
come as undefined.

```
const appState =  {
     employee: fromEmployee.state  // make sure key name is employee
     ...
 }
```

Hope this helps!

**Comment by AnnaLinnIsabelle** [comment]
That solved it!
Thank you so much :smiley:

**Comment by roopkt** [comment]
@AnnaLinnIsabelle you are most welcome 😊
